name: Update Wake-up Chart and README

on:
  schedule:
    - cron: '0 12 * * *' # 每天 UTC 时间 12:00 (北京时间 20:00)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Chinese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-microhei
          fc-list | grep "WenQuanYi Micro Hei"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install matplotlib requests numpy

      - name: Generate chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python generate_chart.py

      - name: Update README with chart
        run: |
          # 检查 README.md 是否包含图片标记
          if grep -q "<!-- WAKE_CHART_PLACEHOLDER -->" README.md; then
            # 如果存在标记，替换标记为图片
            sed -i "s|<!-- WAKE_CHART_PLACEHOLDER -->|![起床时间趋势图](wake_up_chart.png?raw=true \"每日起床时间记录\")|" README.md
          elif grep -q "![起床时间趋势图]" README.md; then
            # 如果已经存在图片，只更新图片文件
            echo "图片已存在，仅更新图片文件"
          else
            # 如果既没有标记也没有图片，在文件末尾添加图片
            echo -e "\n![起床时间趋势图](wake_up_chart.png?raw=true \"每日起床时间记录\")" >> README.md
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add wake_up_chart.png README.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-update wake-up chart"
            git push
          else
            echo "No changes to commit."
          fi
